export const PD1 = {
  fields: [
    {
      desc: "Living Dependency",
      dt: null,
      len: 2,
      opt: "*",
      rp: "",
    },
    {
      desc: "Living Arrangement",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Patient Primary Facility",
      dt: null,
      len: 90,
      opt: "*",
      rp: "",
    },
    {
      desc: "Patient Primary Care Provider Name & ID No.",
      dt: null,
      len: 90,
      opt: "*",
      rp: "",
    },
    {
      desc: "Student Indicator",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Handicap",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Living Will",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Organ Donor",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Separate Bill",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Duplicate Patient",
      dt: null,
      len: 20,
      opt: "*",
      rp: "",
    },
    {
      desc: "Publicity Code",
      dt: null,
      len: 80,
      opt: "1",
      rp: "",
    },
    {
      desc: "Protection Indicator",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
  ],
};
