export const PID = {
  fields: [
    {
      desc: "Set ID – Patient ID",
      dt: null,
      len: 4,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient ID (External ID)",
      dt: null,
      len: 20,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient ID (Internal ID)",
      dt: null,
      len: 20,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Alternate Patient ID – PID",
      dt: null,
      len: 20,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Patient Name",
      dt: null,
      len: 48,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Mother’s Maiden Name",
      dt: null,
      len: 48,
      opt: "",
      rp: "",
    },
    {
      desc: "Date/Time of Birth",
      dt: null,
      len: 26,
      opt: "",
      rp: "",
    },
    {
      desc: "Sex",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient Alias",
      dt: null,
      len: 48,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Race",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient Address",
      dt: null,
      len: 106,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Country Code",
      dt: null,
      len: 4,
      opt: "",
      rp: "",
    },
    {
      desc: "Phone Number – Home",
      dt: null,
      len: 40,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Phone Number – Business",
      dt: null,
      len: 40,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Primary Language",
      dt: null,
      len: 60,
      opt: "",
      rp: "",
    },
    {
      desc: "Marital Status",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
    {
      desc: "Religion",
      dt: null,
      len: 3,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient Account Number",
      dt: null,
      len: 20,
      opt: "",
      rp: "",
    },
    {
      desc: "SSN Number – Patient",
      dt: null,
      len: 16,
      opt: "",
      rp: "",
    },
    {
      desc: "Driver’s License Number - Patient",
      dt: null,
      len: 25,
      opt: "",
      rp: "",
    },
    {
      desc: "Mother’s Identifier",
      dt: null,
      len: 20,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Ethnic Group",
      dt: null,
      len: 3,
      opt: "",
      rp: "",
    },
    {
      desc: "Birth Place",
      dt: null,
      len: 60,
      opt: "",
      rp: "",
    },
    {
      desc: "Multiple Birth Indicator",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Birth Order",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Citizenship",
      dt: null,
      len: 4,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Veterans Military Status",
      dt: null,
      len: 60,
      opt: "",
      rp: "",
    },
    {
      desc: "Nationality",
      dt: null,
      len: 80,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient Death Date and Time",
      dt: null,
      len: 26,
      opt: "",
      rp: "",
    },
    {
      desc: "Patient Death Indicator",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
  ],
};
