export const PV1 = {
  fields: [
    {
      desc: "Set ID – PV1",
      dt: null,
      len: 4,
      opt: "",
      rp: "",
    },
    {
      dt: null,
      len: 1,
      opt: "rm  Patient Class",
      rp: "",
    },
    {
      desc: "Assigned Patient Location",
      dt: null,
      len: 80,
      opt: "",
      rp: "",
    },
    {
      desc: "Admission Type",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Preadmit Number",
      dt: null,
      len: 250,
      opt: "",
      rp: "",
    },
    {
      desc: "Prior Patient Location",
      dt: null,
      len: 80,
      opt: "",
      rp: "",
    },
    {
      desc: "Attending Doctor",
      dt: null,
      len: 250,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Referring Doctor",
      dt: null,
      len: 250,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Consulting Doctor",
      dt: null,
      len: 250,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Hospital Service",
      dt: null,
      len: 3,
      opt: "",
      rp: "",
    },
    {
      desc: "Temporary Location",
      dt: null,
      len: 80,
      opt: "",
      rp: "",
    },
    {
      desc: "Preadmit Test Indicator",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Re admission Indicator",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Admit Source",
      dt: null,
      len: 6,
      opt: "",
      rp: "",
    },
    {
      desc: "Ambulatory Status",
      dt: null,
      len: 2,
      opt: "Y",
      rp: "",
    },
    {
      desc: "VIP Indicator",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Admitting Doctor",
      dt: null,
      len: 250,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Patient Type",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Visit Number",
      dt: null,
      len: 250,
      opt: "",
      rp: "",
    },
    {
      desc: "Financial Class",
      dt: null,
      len: 50,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Charge Price Indicator",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Courtesy Code",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Credit Rating",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Contract Code",
      dt: null,
      len: 2,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Contract Effective Date",
      dt: null,
      len: 8,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Contract Amount",
      dt: null,
      len: 12,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Contract Period",
      dt: null,
      len: 3,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Interest Code",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Transfer to Bad Debt Code",
      dt: null,
      len: 4,
      opt: "",
      rp: "",
    },
    {
      desc: "Transfer to Bad Debt Date",
      dt: null,
      len: 8,
      opt: "",
      rp: "",
    },
    {
      desc: "Bad Debt Agency Code",
      dt: null,
      len: 10,
      opt: "",
      rp: "",
    },
    {
      desc: "Bad Debt Transfer Amount",
      dt: null,
      len: 12,
      opt: "",
      rp: "",
    },
    {
      desc: "Bad Debt Recovery Amount",
      dt: null,
      len: 12,
      opt: "",
      rp: "",
    },
    {
      desc: "Delete Account Indicator",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
    {
      desc: "Delete Account Date",
      dt: null,
      len: 8,
      opt: "",
      rp: "",
    },
    {
      desc: "Discharge Disposition",
      dt: null,
      len: 3,
      opt: "",
      rp: "",
    },
    {
      desc: "Discharged to Location",
      dt: null,
      len: 47,
      opt: "",
      rp: "",
    },
    {
      desc: "Diet Type",
      dt: null,
      len: 250,
      opt: "",
      rp: "",
    },
    {
      desc: "Servicing Facility",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Bed Status",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
    {
      desc: "Account Status",
      dt: null,
      len: 2,
      opt: "",
      rp: "",
    },
    {
      desc: "Pending Location",
      dt: null,
      len: 80,
      opt: "",
      rp: "",
    },
    {
      desc: "Prior Temporary Location",
      dt: null,
      len: 80,
      opt: "",
      rp: "",
    },
    {
      desc: "Admit Date/Time",
      dt: null,
      len: 26,
      opt: "",
      rp: "",
    },
    {
      desc: "Discharge Date/Time",
      dt: null,
      len: 26,
      opt: "Y",
      rp: "",
    },
    {
      desc: "Current Patient Balance",
      dt: null,
      len: 12,
      opt: "",
      rp: "",
    },
    {
      desc: "Total Charges",
      dt: null,
      len: 12,
      opt: "",
      rp: "",
    },
    {
      desc: "Total Adjustments",
      dt: null,
      len: 12,
      opt: "",
      rp: "",
    },
    {
      desc: "Total Payments",
      dt: null,
      len: 12,
      opt: "",
      rp: "",
    },
    {
      desc: "Alternate Visit ID",
      dt: null,
      len: 250,
      opt: "",
      rp: "",
    },
    {
      desc: "Visit Indicator",
      dt: null,
      len: 1,
      opt: "",
      rp: "",
    },
    {
      desc: "Other Healthcare Provider",
      dt: null,
      len: 250,
      opt: "Y",
      rp: "",
    },
  ],
};
