export const PV2 = {
  fields: [
    {
      desc: "Prior Pending Location",
      dt: null,
      len: 80,
      opt: "1",
      rp: "",
    },
    {
      desc: "Accommodation Code",
      dt: null,
      len: 60,
      opt: "1",
      rp: "",
    },
    {
      desc: "Admit Reason",
      dt: null,
      len: 60,
      opt: "1",
      rp: "",
    },
    {
      desc: "Transfer Reason",
      dt: null,
      len: 60,
      opt: "1",
      rp: "",
    },
    {
      desc: "Patient Valuables",
      dt: null,
      len: 25,
      opt: "*",
      rp: "",
    },
    {
      desc: "Patient Valuables Location",
      dt: null,
      len: 25,
      opt: "1",
      rp: "",
    },
    {
      desc: "Visit User Code",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Expected Admit Date/Time",
      dt: null,
      len: 26,
      opt: "1",
      rp: "",
    },
    {
      desc: "Expected Discharge Date/Time",
      dt: null,
      len: 26,
      opt: "1",
      rp: "",
    },
    {
      desc: "Estimated Length of Inpatient Stay",
      dt: null,
      len: 3,
      opt: "1",
      rp: "",
    },
    {
      desc: "Actual Length of Inpatient Stay",
      dt: null,
      len: 3,
      opt: "1",
      rp: "",
    },
    {
      desc: "Visit Description",
      dt: null,
      len: 50,
      opt: "1",
      rp: "",
    },
    {
      desc: "Referral Source Code",
      dt: null,
      len: 90,
      opt: "*",
      rp: "",
    },
    {
      desc: "Previous Service Date",
      dt: null,
      len: 8,
      opt: "1",
      rp: "",
    },
    {
      desc: "Employment Illness Related Indicator",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Purge Status Code",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Purge Status Date",
      dt: null,
      len: 8,
      opt: "1",
      rp: "",
    },
    {
      desc: "Special Program Code",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Retention Indicator",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Expected Number of Insurance Plans",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Visit Publicity Code",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Visit Protection Indicator",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Clinic Organization Name",
      dt: null,
      len: 90,
      opt: "*",
      rp: "",
    },
    {
      desc: "Patient Status Code",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Visit Priority Code",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Previous Treatment Date",
      dt: null,
      len: 8,
      opt: "1",
      rp: "",
    },
    {
      desc: "Expected Discharge Disposition",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Signature on File Date",
      dt: null,
      len: 8,
      opt: "1",
      rp: "",
    },
    {
      desc: "First Similar Illness Date",
      dt: null,
      len: 8,
      opt: "1",
      rp: "",
    },
    {
      desc: "Patient Charge Adjustment Code",
      dt: null,
      len: 80,
      opt: "1",
      rp: "",
    },
    {
      desc: "Recurring Service Code",
      dt: null,
      len: 2,
      opt: "1",
      rp: "",
    },
    {
      desc: "Billing Media Code",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Expected Surgery Date & Time",
      dt: null,
      len: 26,
      opt: "1",
      rp: "",
    },
    {
      desc: "Military Partnership Code",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Military Non-Availability Code",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Newborn Baby Indicator",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
    {
      desc: "Baby Detained Indicator",
      dt: null,
      len: 1,
      opt: "1",
      rp: "",
    },
  ],
};
